"use strict";

export const AVAILABLE_ENEMIES = ["zombie_female","zombie_male"];
export const DIRECTIONS = ["L","R"];
export const MIN_ENEMIES = 2;
export const MAX_ENEMIES = 5;
export const WIDTH_OF_CHARACTERS_IN_CANVAS = 0.08;
export const HEIGHT_OF_CHARACTERS_IN_CANVAS = 0.12;
export const ROOT_PATH_DATA_CHARACTER = "./data/characters";
export const ROOT_PATH_IMAGE_CHARACTER = "./images/characters";
export const GAME_REFRESH_RATE = 30;
export const MAX_FALLING_TIME = 3000;
export const ROOT_PATH_DATA_LEVEL = "./data/levels";
export const SCORE_REQUIRED_TO_CHANGE_LEVEL  = 10;
export const WALK_MAXVELOCITY = 0.005;
export const RUN_MAXVELOCITY = 0.01;
export const FALL_MAXVELOCITY = 0.03;
export const GRAVITY = 0.0025;
export const FRICTION_COEFFICIENT = 0.8;
export const COOLDOWN_BETWEEN_PAUSES = 1000;
export const DELAY_BEFORE_ENEMY_STATE_CHANGE = 5000;
export const PROBABILITY_OF_ENEMY_APPEARANCE = 0.01;
export const DELAY_BEFORE_NEXT_ENEMY_APPEARANCE = 5000;